---
# mosquitto.yml - Mosquitto MQTT broker deployment
# Assumes IP is configured via DHCP (cloud-init default or Terraform DHCP)
- name: Deploy and configure Mosquitto MQTT broker
  hosts: iot_servers
  vars:
    mosquitto_config_dir: /etc/mosquitto
    mosquitto_data_dir: /var/lib/mosquitto
    mosquitto_log_dir: /var/log/mosquitto
    mosquitto_container_name: mosquitto

  tasks:
    # --------------------------------------------------------------------------
    # Wait for System Readiness
    # --------------------------------------------------------------------------
    - name: Wait for apt/dpkg locks to be released
      ansible.builtin.shell: while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done
      changed_when: false
      timeout: 300  # 5 minute timeout
      # become: yes # Might not be needed if user can run lsof

    - name: Wait for cloud-init to complete
      ansible.builtin.shell: while [ ! -f /var/lib/cloud/instance/boot-finished ]; do sleep 5; done
      changed_when: false
      timeout: 300  # 5 minute timeout

    # --------------------------------------------------------------------------
    # Docker Installation
    # --------------------------------------------------------------------------
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install required dependencies for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker # Explicit filename
      become: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
      register: docker_install_result
      until: docker_install_result is succeeded
      retries: 5
      delay: 15
      become: yes

    - name: Make sure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add deployment user to docker group for non-sudo docker commands
      ansible.builtin.user:
        name: "{{ ansible_user | default('nathan') }}" # Use ansible_user which is 'nathan' from ansible.cfg
        groups: docker
        append: yes
      become: yes

    # --------------------------------------------------------------------------
    # Mosquitto Configuration
    # --------------------------------------------------------------------------
    - name: Create Mosquitto configuration directory
      ansible.builtin.file:
        path: "{{ mosquitto_config_dir }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Create Mosquitto data directory with correct permissions
      ansible.builtin.file:
        path: "{{ mosquitto_data_dir }}"
        state: directory
        owner: '1883'  # Mosquitto container user UID
        group: '1883'  # Mosquitto container user GID
        mode: '0755'
      become: yes

    - name: Create Mosquitto log directory with correct permissions
      ansible.builtin.file:
        path: "{{ mosquitto_log_dir }}"
        state: directory
        owner: '1883'  # Mosquitto container user UID
        group: '1883'  # Mosquitto container user GID
        mode: '0755'
      become: yes

    - name: Deploy Mosquitto configuration
      ansible.builtin.copy:
        dest: "{{ mosquitto_config_dir }}/mosquitto.conf"
        content: |
          # Mosquitto MQTT Broker Configuration

          # Persistence settings
          persistence true
          persistence_location /mosquitto/data

          # Logging
          log_dest file /mosquitto/log/mosquitto.log
          log_type all

          # Network settings
          listener 1883

          # Security (for development - allowing anonymous access)
          allow_anonymous true

          # Include additional config files
          include_dir /mosquitto/config/conf.d
        mode: '0644'
      become: yes

    - name: Create conf.d directory for additional config files
      ansible.builtin.file:
        path: "{{ mosquitto_config_dir }}/conf.d"
        state: directory
        mode: '0755'
      become: yes

    # --------------------------------------------------------------------------
    # Mosquitto Docker Container
    # --------------------------------------------------------------------------
    - name: Pull Mosquitto Docker image
      community.docker.docker_image:
        name: eclipse-mosquitto:latest
        source: pull
      become: yes

    - name: Start Mosquitto container
      community.docker.docker_container:
        name: "{{ mosquitto_container_name }}"
        image: eclipse-mosquitto:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "1883:1883"  # MQTT
          - "9001:9001"  # WebSockets (if needed)
        volumes:
          # Config mounts are read-write to allow entrypoint script chown
          - "{{ mosquitto_config_dir }}/mosquitto.conf:/mosquitto/config/mosquitto.conf"
          - "{{ mosquitto_config_dir }}/conf.d:/mosquitto/config/conf.d"
          # Data and log volumes remain read-write
          - "{{ mosquitto_data_dir }}:/mosquitto/data:rw"
          - "{{ mosquitto_log_dir }}:/mosquitto/log:rw"
        restart: yes # Ensures container restarts if stopped manually or on error (unless stopped)
      become: yes # Run docker commands as root

    # --------------------------------------------------------------------------
    # Verification
    # --------------------------------------------------------------------------
    # Note: Installing clients on host is not strictly needed for docker exec check,
    # but can be useful for manual host debugging. Keep it for now.
    - name: Install mosquitto-clients for testing (on host)
      ansible.builtin.apt:
        name: mosquitto-clients
        state: present
      become: yes

    - name: Wait a few seconds for Mosquitto service inside container to stabilize
      ansible.builtin.pause:
        seconds: 5 # Adjust as needed, start with 5 seconds

    - name: Verify Mosquitto is running (via docker exec)
      # Execute mosquitto_sub inside the container with debug, check output for CONNACK
      ansible.builtin.command: docker exec {{ mosquitto_container_name }} mosquitto_sub -h localhost -t 'test/topic' -C 1 -W 3 -d
      register: mqtt_test_exec # Register the whole result
      changed_when: false
      failed_when: false # Don't fail the playbook if test fails
      ignore_errors: true # Continue even if test fails
      become: yes # Use become to ensure user can run 'docker exec'

    - name: Check verification command output for success
      # Check if the stdout from the command contains the CONNACK message
      ansible.builtin.set_fact:
        mqtt_connected: "{{ 'CONNACK' in mqtt_test_exec.stdout }}"

    - name: Show MQTT connection status
      ansible.builtin.debug:
        # Use the mqtt_connected fact to determine success
        msg: "MQTT broker status: {{ 'Connected successfully (verified via docker exec)' if mqtt_connected else 'Connection failed - check container logs or docker exec command output' }}"
        # You can uncomment the line below to see the full output of the verification command for debugging
        # var: mqtt_test_exec

# --- Handlers Section Removed ---
